CREATE TABLE IF NOT EXISTS "_supavisor"."tenants"(
 "id" uuid   NOT NULL ,
 "external_id" character varying(255)   NOT NULL ,
 "db_host" character varying(255)   NOT NULL ,
 "db_port" integer   NOT NULL ,
 "db_database" character varying(255)   NOT NULL ,
 "inserted_at" timestamp(0) without time zone   NOT NULL ,
 "updated_at" timestamp(0) without time zone   NOT NULL ,
 "default_parameter_status" jsonb   NOT NULL ,
 "ip_version" character varying(255)  DEFAULT 'auto'::character varying   NOT NULL ,
 "upstream_ssl" boolean  DEFAULT false   NOT NULL ,
 "upstream_verify" character varying(255)   ,
 "upstream_tls_ca" bytea   ,
 "enforce_ssl" boolean  DEFAULT false   NOT NULL ,
 "require_user" boolean  DEFAULT true   NOT NULL ,
 "auth_query" character varying(255)   ,
 "default_pool_size" integer  DEFAULT 15   NOT NULL ,
 "sni_hostname" character varying(255)   ,
 "default_max_clients" integer  DEFAULT 1000   NOT NULL ,
 "client_idle_timeout" integer  DEFAULT 0   NOT NULL ,
 "default_pool_strategy" character varying(255)  DEFAULT 'fifo'::character varying   NOT NULL ,
 "client_heartbeat_interval" integer  DEFAULT 60   NOT NULL ,
 "allow_list" character varying(255)[]  DEFAULT ARRAY['0.0.0.0/0'::character varying, '::/0'::character varying]   NOT NULL ,
 "availability_zone" character varying(255)   
);
