CREATE TABLE IF NOT EXISTS "_analytics"."users"(
 "id" bigserial   NOT NULL ,
 "email" character varying(255)   ,
 "provider" character varying(255)   NOT NULL ,
 "token" text   NOT NULL ,
 "inserted_at" timestamp(0) without time zone   NOT NULL ,
 "updated_at" timestamp(0) without time zone   NOT NULL ,
 "api_key" character varying(255)   NOT NULL ,
 "old_api_key" character varying(255)   ,
 "email_preferred" character varying(255)   ,
 "name" character varying(255)   ,
 "image" character varying(255)   ,
 "email_me_product" boolean  DEFAULT true   NOT NULL ,
 "admin" boolean  DEFAULT false   NOT NULL ,
 "phone" character varying(255)   ,
 "bigquery_project_id" character varying(255)   ,
 "api_quota" integer  DEFAULT 125   NOT NULL ,
 "bigquery_dataset_location" character varying(255)   ,
 "bigquery_dataset_id" character varying(255)   ,
 "valid_google_account" boolean   ,
 "provider_uid" text   NOT NULL ,
 "company" character varying(255)   ,
 "bigquery_udfs_hash" character varying(255)  DEFAULT ''::character varying   NOT NULL ,
 "bigquery_processed_bytes_limit" bigint  DEFAULT '10000000000'::bigint   NOT NULL ,
 "billing_enabled?" boolean  DEFAULT false   NOT NULL ,
 "preferences" jsonb   ,
 "billing_enabled" boolean  DEFAULT false   NOT NULL ,
 "endpoints_beta" boolean  DEFAULT false   ,
 "metadata" jsonb   ,
 "partner_upgraded" boolean  DEFAULT false   ,
 "partner_id" bigint   ,
 "bigquery_enable_managed_service_accounts" boolean  DEFAULT false   ,
 "bigquery_reservation_search" character varying(255)   ,
 "bigquery_reservation_alerts" character varying(255)   
);
