CREATE TABLE IF NOT EXISTS "kong"."routes"(
 "id" uuid   NOT NULL ,
 "created_at" timestamp with time zone   ,
 "updated_at" timestamp with time zone   ,
 "name" text   ,
 "service_id" uuid   ,
 "protocols" text[]   ,
 "methods" text[]   ,
 "hosts" text[]   ,
 "paths" text[]   ,
 "snis" text[]   ,
 "sources" jsonb[]   ,
 "destinations" jsonb[]   ,
 "regex_priority" bigint   ,
 "strip_path" boolean   ,
 "preserve_host" boolean   ,
 "tags" text[]   ,
 "https_redirect_status_code" integer   ,
 "headers" jsonb   ,
 "path_handling" text  DEFAULT 'v0'::text   ,
 "ws_id" uuid   ,
 "request_buffering" boolean   ,
 "response_buffering" boolean   ,
 "expression" text   ,
 "priority" bigint   
);
