CREATE TABLE IF NOT EXISTS "_analytics"."sources"(
 "id" bigserial   NOT NULL ,
 "name" character varying(255)   ,
 "token" uuid   NOT NULL ,
 "inserted_at" timestamp(0) without time zone   NOT NULL ,
 "updated_at" timestamp(0) without time zone   NOT NULL ,
 "user_id" integer   NOT NULL ,
 "public_token" character varying(255)   ,
 "favorite" boolean  DEFAULT false   NOT NULL ,
 "bigquery_table_ttl" integer   ,
 "api_quota" integer  DEFAULT 5   NOT NULL ,
 "webhook_notification_url" character varying(255)   ,
 "slack_hook_url" character varying(255)   ,
 "notifications" jsonb  DEFAULT '{"team_user_ids_for_sms": [], "team_user_ids_for_email": [], "user_text_notifications": false, "user_email_notifications": false, "other_email_notifications": null, "team_user_ids_for_schema_updates": [], "user_schema_update_notifications": true}'::jsonb   NOT NULL ,
 "custom_event_message_keys" character varying(255)   ,
 "log_events_updated_at" timestamp(0) without time zone   ,
 "bigquery_schema" bytea   ,
 "notifications_every" integer  DEFAULT 14400000   ,
 "bq_table_partition_type" text   ,
 "lock_schema" boolean  DEFAULT false   ,
 "validate_schema" boolean  DEFAULT true   ,
 "drop_lql_filters" bytea  DEFAULT '\x836a'::bytea   NOT NULL ,
 "drop_lql_string" character varying(255)   ,
 "v2_pipeline" boolean  DEFAULT false   ,
 "suggested_keys" character varying(255)  DEFAULT ''::character varying   ,
 "service_name" character varying(255)   ,
 "transform_copy_fields" character varying(255)   ,
 "disable_tailing" boolean  DEFAULT false   ,
 "bq_storage_write_api" boolean  DEFAULT false   ,
 "bigquery_clustering_fields" character varying(255)   ,
 "default_ingest_backend_enabled" boolean  DEFAULT false   
);
