CREATE TABLE IF NOT EXISTS "kong"."upstreams"(
 "id" uuid   NOT NULL ,
 "created_at" timestamp with time zone  DEFAULT (CURRENT_TIMESTAMP(3) AT TIME ZONE 'UTC'::text)   ,
 "name" text   ,
 "hash_on" text   ,
 "hash_fallback" text   ,
 "hash_on_header" text   ,
 "hash_fallback_header" text   ,
 "hash_on_cookie" text   ,
 "hash_on_cookie_path" text   ,
 "slots" integer   NOT NULL ,
 "healthchecks" jsonb   ,
 "tags" text[]   ,
 "algorithm" text   ,
 "host_header" text   ,
 "client_certificate_id" uuid   ,
 "ws_id" uuid   ,
 "hash_on_query_arg" text   ,
 "hash_fallback_query_arg" text   ,
 "hash_on_uri_capture" text   ,
 "hash_fallback_uri_capture" text   ,
 "use_srv_name" boolean  DEFAULT false   ,
 "updated_at" timestamp with time zone  DEFAULT (CURRENT_TIMESTAMP(0) AT TIME ZONE 'UTC'::text)   
);
