CREATE DATABASE supabase_db;
\c supabase_db;
CREATE TYPE "action" AS ENUM ('INSERT', 'UPDATE', 'DELETE', 'TRUNCATE', 'ERROR');
CREATE TYPE "oauth_client_type" AS ENUM ('public', 'confidential');
CREATE TYPE "oauth_registration_type" AS ENUM ('dynamic', 'manual');
CREATE TYPE "aal_level" AS ENUM ('aal1', 'aal2', 'aal3');
CREATE TYPE "factor_type" AS ENUM ('totp', 'webauthn', 'phone');
CREATE TYPE "equality_op" AS ENUM ('eq', 'neq', 'lt', 'lte', 'gt', 'gte', 'in');
CREATE TYPE "one_time_token_type" AS ENUM ('confirmation_token', 'reauthentication_token', 'recovery_token', 'email_change_token_new', 'email_change_token_current', 'phone_change_token');
CREATE TYPE "factor_status" AS ENUM ('unverified', 'verified');
CREATE TYPE "oauth_response_type" AS ENUM ('code');
CREATE TYPE "code_challenge_method" AS ENUM ('s256', 'plain');
CREATE TYPE "request_status" AS ENUM ('PENDING', 'SUCCESS', 'ERROR');
CREATE TYPE "oauth_authorization_status" AS ENUM ('pending', 'approved', 'denied', 'expired');
